### ISSUE TITLE
JS Error after installation

### ISSUE THREAD

**Issue by snipestyle9410** [kalkih/simple-weather-card#56]
I just installed the card through hacs. Unfortunately it seems to not be working.

Tried it in multiple HA versions and browsers. Don't know if i missed something.
Also followed the configuration instructions.

Card Configuration:
type: custom:simple-weather-card
entity: weather.home
name: in current location

JS Console Error: 
`simple-weather-card-bundle.js?hacstag=172998062080:1 Uncaught TypeError: A is not a function
    at i (simple-weather-card-bundle.js?hacstag=172998062080:1:33169)
    at Function.get styles [as styles] (simple-weather-card-bundle.js?hacstag=172998062080:1:3180)
    at Function.finalize (styles.ts:368:1)
    at Function.get observedAttributes [as observedAttributes] (styles.ts:368:1)
    at window.CustomElementRegistry.define (typography.js:181:1)
    at Object.<anonymous> (simple-weather-card-bundle.js?hacstag=172998062080:1:2922)
    at e (simple-weather-card-bundle.js?hacstag=172998062080:1:110)
    at simple-weather-card-bundle.js?hacstag=172998062080:1:902
    at simple-weather-card-bundle.js?hacstag=172998062080:1:911`

**Comment by kalkih** [comment]
Closing for #57
